### ISSUE TITLE
Add examples of dumps

### ISSUE THREAD

**Issue by verysimplenick** [ModDota/D2VDump#1]
Hi, add examples of dumps. It's big time saving for visitors.

**Comment by SinZ163** [comment]
The examples of dumps can be found at https://github.com/moddota/api/blob/master/_data/

though panorama_enums.json is manual and not part of this repository

EDIT:  
* `out0.json` maps to `lua_server.json`
* `value0.json` maps to `lua_server_enums.json`
* `out1.json` maps to `lua_bots.json` (NOTE: Not currently possible without other libraries currently)
* `value1.json` maps to `lua_bots_enums.json` (NOTE: Not currently possible without other libraries currently)
